### ISSUE TITLE
worldwide image to tiles

### ISSUE THREAD

**Issue by jsbrujy** [Gigas002/GTiff2Tiles#108]
Hello

I tried to generate Tiles for a single gtiff image covering -180 -90 to 180 90 (Natural Earth II image). Border coordinates are correctely rounded
An exception appears with index generated to be -1 when >= 0 is expected

Did you already tried to generate tiles for a worldwide image? Should it be running?

thanks

BR

**Comment by Gigas002** [comment]
Hello, @jsbrujy!
Could you please provide more information, e.g:

- Which version of GTiff2Tiles you're running (console/gui; version number);
- OS (Win/Linux);
- Run arguments (`minz`, `maxz`, etc);

Also, please share an input geotiff is you have an ability, so I'll spot the error faster.

**Comment by jsbrujy** [comment]
Hello Gigas002

I am running the GUI version 2.0.0.669 on Win10
input tiff file is NE2_HR_LC_SR_W_DR.tif (https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/raster/NE2_HR_LC_SR_W.zip)

zoom levels selected 1-5
TMS compatible checked

You will have to take care of the geotiff coordinates. They are not perfectly rounded at -180, -90, 180 and 90. I rounded it using gdalwarp. Perhaps something that could be managed by GTiff2Tiles???

thanks

**Comment by Gigas002** [comment]
I've located an error, it'll be fixed in the upcoming continious build. Thank you for your report!
Concerning out-of-bounds input image, it's an unusual situation for input files, so I'm guessing the user should still see the error about it without changing something automatically.

**Comment by jsbrujy** [comment]
sounds great.
really appreciate for your really fast investigation and fix

well done Gigas002 !!!!

**Comment by jsbrujy** [comment]
working perfectly now when generating zoom 0 to 6 

Again thank you Gigas002

**Comment by Gigas002** [comment]
@jsbrujy

Glad it helped! I'll close this issue, when I'll add some test data and test code for project, regarding this problem.

But beware of creating 14+ zoom lvl tiles for worldwide geotiff, there's still an issue that I didn't fix yet (see #111).

**Comment by Gigas002** [comment]
No tests for this bugfix due to large size of geotiff.
