### ISSUE TITLE
NetVips file opening issue

### ISSUE THREAD

**Issue by FurqanMehmood** [Gigas002/GTiff2Tiles#4]
**Describe the bug**
I want to generate tiles from mosaic, i am passing arguments to console but i got this error 
"NetVips is unable to open input image.
An attempt was made to load a program with an incorrect format. (Exception from
HRESULT: 0x8007000B)"

**Expected behavior**
The expacted behvaiour will be the tiles in output folder 

**Screenshots**
![netvips](https://user-images.githubusercontent.com/32258657/58230063-b4740680-7d4c-11e9-9942-bda7786e92f7.png)

**Desktop (please complete the following information):**
 - OS: [Windows 8]

**Comment by Gigas002** [comment]
Hello.
What exactly do you mean by mosaic, Is it a set of GeoTIFFs? Currently, the only supported input data extension is `.tif` (GeoTIFF). Also, please tell me the arguments you were using.

**Comment by FurqanMehmood** [comment]
yes i am passing a .tif image. and passing just input location and temp directory path and output directory path

**Comment by Gigas002** [comment]
Could you please provide that GeoTIFF?

**Comment by FurqanMehmood** [comment]
i can not upload  .tif files here because Github does not support .tif files

**Comment by Gigas002** [comment]
Consider compressing GeoTIFF into `.zip` archive and uploading it into Github, or using file sharing systems (e.g. Google Drive).

**Comment by FurqanMehmood** [comment]
You can copy .zip from here ,here is google drive link
https://drive.google.com/open?id=1qQbNoBoOlYFcgTk0Cv-ZyqVqdrNstUSm

**Comment by Gigas002** [comment]
Thank you for your data. I found out the error, it's similar to #3 issue. I'll contact NetVips developer and fix this as soon as I can.

**Comment by Gigas002** [comment]
Feel free to reopen issue if you have some questions remaining.
