### ISSUE TITLE
Creating Tiles issue

### ISSUE THREAD

**Issue by FurqanMehmood** [Gigas002/GTiff2Tiles#5]
**Describe the bug**
I want to create tiles of a 4 band geotiff file. i am using the GUI of project. when i enter zoom level 0 to 23. it generates zoom level 23 empty folders in output and gives me following error
"unable to call insert unknown pseudo-tag 65538 
insert image must have the same number of bands, or one must be single"

![geotiff2tiles](https://user-images.githubusercontent.com/32258657/58232509-19caf600-7d53-11e9-96e1-c3e83ce8bd41.PNG)

**Comment by Gigas002** [comment]
Hello.
Do you use [1.2.0 release](https://github.com/Gigas002/GTiff2Tiles/releases/tag/v1.2.0)? Also it would be a very helpfull if you could provide that GeoTIFF sample for me to test it. I'm not sure I can reproduce that error without data.

**Comment by FurqanMehmood** [comment]
no i am building from source

**Comment by Gigas002** [comment]
Could you please provide that or similar GeoTIFF, that causes that error? I think I know what causes that error, but that would be good to test it on your data.

**Comment by FurqanMehmood** [comment]
here is link to file https://drive.google.com/open?id=1MsAUENX1SKSsCMZBo49s6sS0SP_ICMNJ

**Comment by Gigas002** [comment]
Thank you for your data. I found out and fixed that error with latest commit.
Though I should warn you, that high level tiles (approximately 0-10 zooms in case of that **GeoTIFF**) doesn't work correctly because of #3. I advise you to use `join` algorithm while it's not fixed (`-a "join"` parameter instead of `-a "crop"` in `GTiff2Tiles.Console` or `join` algorithm in `GTiff2Tiles.GUI`).

**Comment by FurqanMehmood** [comment]
i am using python version of gdal2tiles using osgeo4 shell, and that creates tiles for zoom 15 to 20.

**Comment by FurqanMehmood** [comment]
![issue](https://user-images.githubusercontent.com/32258657/58574951-9f223f00-825a-11e9-976b-d84107648f47.PNG)
i also input minimum zoom level 0 and maximum 10, but i am having same issue

**Comment by FurqanMehmood** [comment]
Image.cs line 94 **Helpers.NetVipsHelper.DisableLog();** throws this exception

**Comment by Gigas002** [comment]
This error occurs if you build the soultion in VS targeting `Any CPU` platform. You should choose `x64` platform for every project in solution.
![image](https://user-images.githubusercontent.com/24297712/58576541-3e403a00-824d-11e9-8dbc-b9de45597a64.png)

**Comment by FurqanMehmood** [comment]
Can i get mercator projected tiles

**Comment by Gigas002** [comment]
Currently, only `EPSG:4326` tiles on output are supported.

**Comment by FurqanMehmood** [comment]
do you have any intentions to generate mercator tiles

**Comment by Gigas002** [comment]
Probably I'll add this feature, but not in the near future.

**Comment by Gigas002** [comment]
I've fixed that (and #3, #4) issues with https://github.com/Gigas002/GTiff2Tiles/commit/e42e5aecc9bf42e2329dade4a9bc1575f006a4fc. Please, try it out when you'll have time and tell me, if it works fine.

**Comment by Gigas002** [comment]
Feel free to reopen issue if you have some questions remaining.
