### ISSUE TITLE
Tiles for EPSG:3857

### ISSUE THREAD

**Issue by FurqanMehmood** [Gigas002/GTiff2Tiles#8]
I use gdal2tiles.py to generate tiles in mercator projection, and those tiles fits very well on google map, i want gdal2tiles.py implementation . can you add this feature in your project.

**Comment by Gigas002** [comment]
Hello.
Yes, this is a planned feature, I've already created #6 in this regards. Yet I cannot tell any timing on when it'll be ready.

**Comment by Gigas002** [comment]
As I said in #6 , work in Core for this feature complete and new options will appear in new stable release in both Console and GUI apps. 
To avoid confusion, I'm closing this issue.
