### ISSUE TITLE
Generate tilemapresource.xml

### ISSUE THREAD

**Issue by zhongshuiyuan** [Gigas002/GTiff2Tiles#94]
Can not generates tilemapresource.xml.

**Comment by Gigas002** [comment]
Hello. Currently I don't create any other files, except tile images. It's a good idea to add creation of such an xml file, I'll consider working on it for 2.1.x update!

**Comment by zhongshuiyuan** [comment]
It would be great if could create this file. I tried to publish the tiles to GeoServer, it was missing tilemapresource.xml and could not published.

**Comment by Gigas002** [comment]
Roadmap for feature:

Core:

- [ ] Implement classes for serialization/deserialization;
- [ ] Write all precondition checks;
- [ ] Complete xml-docs;

Tests:

- [ ] Complete tests for this feature and fix errors if any;
- [ ] Update code coverage;

Console:

- [ ] Add an arument to create `tilemapresource.xml` after creating tiles;

GUI:

- [ ] Add an option to create `tilemapresource.xml` after creating tiles;

Docs:

- [ ] Update CHANGELOG.md;
- [ ] Update Console docs;
- [ ] Update GUI docs;
- [ ] Rebuild github pages docs with docfx;

**Comment by zhongshuiyuan** [comment]
Thanks，Very helpful
