### ISSUE TITLE
Broken linux build with GDAL 3.2.0

### ISSUE THREAD

**Issue by Gigas002** [Gigas002/GTiff2Tiles#98]
According to https://github.com/MaxRev-Dev/gdal.netcore/commit/76b614c3af317babd078579de40a940cc8ce8730#diff-6d6fa00a963a2026bc7d3d2ee4486b1eb68f25bbb6e14b9164de138aca393cde, it's currently impossible to use gdal with libtiff on linux due to some problems with other dependencies. I'll continue using 3.1.2 until this'll be fixed.

**Comment by MaxRev-Dev** [comment]
@Gigas002 I can't see the problem. With v3.2.0, we use gdal's internal `libtiff` again as in previous versions before `vcpkg `was integrated.

**Comment by MaxRev-Dev** [comment]
Release PR changelog. https://github.com/MaxRev-Dev/gdal.netcore/pull/29#issue-538359893
And related diff: https://github.com/MaxRev-Dev/gdal.netcore/pull/29/commits/9ff51790b4eda584a27b0745cac15518c1e4f4f5#diff-03d0ba484a254fdcff6386b477fb6fc98647d98368cae9b22219dcb1abc2b0be

**Comment by Gigas002** [comment]
Hmm. Thanks for your reply, I'll take a look at these. Unit tests for my project in [CI on linux](https://github.com/Gigas002/GTiff2Tiles/runs/1551519159?check_suite_focus=true) failed on the last gdal update, I thought that might be the issue.

**Comment by Gigas002** [comment]
Oh, by the way it [was still bugged](https://github.com/Gigas002/GTiff2Tiles/runs/1551519159?check_suite_focus=true), when I used previous `LinuxRuntime` package (3.1.2.110) with newer `WindowsRuntime` and `Core` (3.2.0.100/3.2.0.100). Probably a bug in core? I'll research more into this.

**Comment by MaxRev-Dev** [comment]
I don't think this is related, but the latest version for windows (110) is a patch for the cached GEOS 3.8.0 (this was also in [changelog](https://github.com/MaxRev-Dev/gdal.netcore/pull/29/commits/888b4eecfc006d871a9c2eaaa812c3f3ec6b9925#diff-52a62c9e80c5e656d6f20f830d05c92b9d50bf499467d019674cfbd5b0b99c00)). That's because I'm building it locally without CI, and did not configured travis yet. But still GEOS was updated to 3.9.0beta2.
I agree, that should be a bug in core bindings. But windows part works just fine, despite the core was built from linux.

**Comment by MaxRev-Dev** [comment]
Created an issue for this https://github.com/MaxRev-Dev/gdal.netcore/issues/30

**Comment by Gigas002** [comment]
@MaxRev-Dev Ran through some tests on Ubuntu-20.04. Updated only `LinuxRuntime` to `3.2.0.100` with `Core` version `3.1.2.110` tests runs fine. After updating the core lib something breaks, can't tell, what exactly (most tests passes still). So it seems more like core bug.

**Comment by Gigas002** [comment]
Located one of errors:

```cs
        public static string GetProjString(string inputFilePath)
        {
            GdalBase.ConfigureAll();

            using Dataset dataset = Gdal.Open(inputFilePath, Access.GA_ReadOnly);

            string wkt = dataset.GetProjection();

            using SpatialReference spatialReference = new SpatialReference(wkt);

            spatialReference.ExportToProj4(out string projString);

            return projString;
        }
```

The `string wkt = dataset.GetProjection();` returns empty string.

**Comment by Gigas002** [comment]
`GdalWarp` breaks too, probably because it can't get the projection to translate.

**Comment by MaxRev-Dev** [comment]
@Gigas002 Please, checkout the latest patch (110) of core at [nuget](https://www.nuget.org/packages/MaxRev.Gdal.Core/3.2.0.110).

**Comment by Gigas002** [comment]
Nice! I can see, that `Gdal.Warp` methods is now... well, `Warp`, not `wrapper_GDALWarpDestName`. I like it, even though I don't understand why does it take an array of `Dataset`s.
Tests on my local windows machine passed, pushing to the github to see linux's test result.

**Comment by Gigas002** [comment]
@MaxRev-Dev Weird, that doesn't seem to fix an issue. I'll check this out on my ubuntu VM as well tomorrow. For now, judjing by ci output, I can see, that the `projString` is still empty.

**Comment by MaxRev-Dev** [comment]
@Gigas002 I see that did not helped.
But linux bindings are fine now, [that test with proj string](
https://github.com/MaxRev-Dev/gdal.netcore/blob/master/test/GdalCore-XUnit/CommonTests.cs#L68-L76) is passing (in WSL CentOS7). 

<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/24393967/102133586-fcdaa400-3e5d-11eb-9833-485b49b0bb8b.png)

</details>

**Comment by Gigas002** [comment]
@MaxRev-Dev Nope, that little test with `projString` still doesn't work under ubuntu 20.04, don't know why. Gdal seems to be configured well and the created `Dataset` works fine. What additional info can I provide to you?

**Comment by MaxRev-Dev** [comment]
Yeah, that's weird, `projString` test works fine on CentOS7. Ok, I will try this on Ubuntu 20.04 in WSL.

**Comment by MaxRev-Dev** [comment]
Just installed a clean distro. Can't repro with my packages.
Can you make a minimal workable sample or test of this, and maybe make a PR in main repo?

<details>
<summary>Logs </summary>

![image](https://user-images.githubusercontent.com/24393967/102261676-abdcb580-3f1a-11eb-9e25-a4f26a061e7b.png)


</details>

**Comment by Gigas002** [comment]
@MaxRev-Dev Not sure, why your test is passing, but I have a guess: you're using `Assert.NotNull(projString);` in the end, and the string is actually not null -- it's just an empty string. It would be better to write something like `Assert.False(string.IsNullOrWhiteSpace)` .
I'm running the app as console app. Here's my `.csproj`:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>x64</Platforms>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaxRev.Gdal.Core" Version="3.2.0.110" />
    <PackageReference Include="MaxRev.Gdal.LinuxRuntime.Minimal" Version="3.2.0.100" />
  </ItemGroup>

</Project>
```

And code in `Program.cs`:

```cs
using System;
using MaxRev.Gdal.Core;
using OSGeo.GDAL;
using OSGeo.OSR;

namespace GdalTest
{
    class Program
    {
        public static void Main(string[] args)
        {
            var inputFile = "/home/gigas002/dotnet-tests/Input4326.tif";
            var projString = GetProjString(inputFile);
            Console.WriteLine($"projstring:{projString}");
        }

         public static string GetProjString(string inputFilePath)
        {
            GdalBase.ConfigureAll();

            using Dataset dataset = Gdal.Open(inputFilePath, Access.GA_ReadOnly);

            string wkt = dataset.GetProjection();

            Console.WriteLine($"wkt:{wkt}");

            using SpatialReference spatialReference = new SpatialReference(wkt);

            spatialReference.ExportToProj4(out string projString);

            return projString;
        }
    }
}
```

**Comment by MaxRev-Dev** [comment]
> `Assert.NotNull(projString);`
Thanks for pointing on this, that makes sense. Did not expected that return value from bindings, thought it should be a null ref. 
But currently, It does not bring to me any information, what did happened on linux in gdal320.

**Comment by MaxRev-Dev** [comment]
That's interesting. But [updated test](https://github.com/MaxRev-Dev/gdal.netcore/blob/b3d72d6be5119165ca9660c0479c6cb59c80f730/test/GdalCore-XUnit/CommonTests.cs#L46-L59) does not passing now, at all. Even on windows, even with previous packages.

<details>
<summary> Windows Logs </summary>

![image](https://user-images.githubusercontent.com/24393967/102267714-fbbf7a80-3f22-11eb-9090-d2da8e595bc0.png)

</details>

**Comment by MaxRev-Dev** [comment]
I think, I figured out what the problem is, so we are very close to solution. 
That should be a shared `proj.db` between both runtimes.
Going to investigate this further tomorrow.
Thank you for you help.

**Comment by MaxRev-Dev** [comment]
@Gigas002 I had already rebuilt packages. Please, checkout the latest version.

**Comment by Gigas002** [comment]
@MaxRev-Dev Sorry, I didn't have a chance to answer and run tests sooner. I've run that test of getting string from proj and it worked, but still not all tests have passed for my app (17 failed, was 22). Some tests throw ` System.ApplicationException: PROJ: proj_create_from_database: Cannot find proj.db`, and some fail on `GdalWarp`. Here's an example of failing `GdalInfo` method with above excpetion:

```cs
        public static string GdalInfo(string inputFilePath, string[] options = null)
        {
            GdalBase.ConfigureAll();

            using Dataset inputDataset = Gdal.Open(inputFilePath, Access.GA_ReadOnly);

            return Gdal.GDALInfo(inputDataset, new GDALInfoOptions(options));
        }
```

**Comment by MaxRev-Dev** [comment]
@Gigas002 Thanks for new info. I had adjusted tests and rewrote `proj.db` search algorithm.
Patch is already published as `MaxRev.Gdal.Core.3.2.0.210`

**Comment by Gigas002** [comment]
@MaxRev-Dev Seems to work correctly in WSL. Pushing to see the changes in CI.

**Comment by Gigas002** [comment]
Yes, all the tests have passed successfully. Thanks a lot for your help with this issue!
